/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.aiaiyo;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    /**
        * The main method of the application.
        * This method is the entry point of the program.
        * It prints the greeting message returned by the getGreeting method.
        *
        * @param args The command-line arguments passed to the program.
        */
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
